version: "3.8"

services:
    db:
      image: postgres
      volumes:
        - postgres_db:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=bot_pvc_db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - PG_HOST=db

      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5

    bot_run:
      image: ghcr.io/p0lygun/pvc/bot:latest
      command: "python -m bot"

      environment:
        - PVC_TOKEN=${PVC_TOKEN}

      deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s

      depends_on:
        db:
          condition: service_healthy

volumes:
   postgres_db: